apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | quote }}
  TG_BOT_TOKEN: {{ .Values.secret.TG_BOT_TOKEN | quote }}
