# Number of replicas for the app deployment
replicaCount: 2

image:
  repository: ghcr.io/kpi-kujo205/ecommerce-app
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"

service:
  type: ClusterIP
  port: 80
  targetPort: 4000

config:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "mydatabase"
  DB_USER: "user"
  PORT: "4000"
  NODE_ENV: "production"
  BASE_URL: "http://localhost:4000"

secret:
  DB_PASSWORD: "password"
  TG_BOT_TOKEN: ""

postgres:
  image: postgres:13-alpine
  port: 5432
