/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Birthdays {
  birth_day: number;
  birth_month: number;
  birth_year: number | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  name: string | null;
  remind_1_week_before: Generated<boolean>;
  remind_3_days_before: Generated<boolean>;
  remind_on_day: Generated<boolean>;
  telegram_username: string | null;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
}

export interface ReminderLogs {
  birthday_id: string;
  id: Generated<string>;
  sent_at: Generated<Timestamp>;
  type: string;
  year: number;
}

export interface Users {
  created_at: Generated<Timestamp>;
  first_name: string | null;
  id: Int8;
  tg_user_json: Json;
  timezone: Generated<string>;
  username: string | null;
}

export interface DB {
  birthdays: Birthdays;
  reminder_logs: ReminderLogs;
  users: Users;
}
